### ISSUE TITLE
IPA crashes on launch, tweak doesn't inject. (iOS 14.3)

### ISSUE THREAD

**Issue by Lost-Entrepreneur439** [bunny-mod/BunnyTweak#14]
I'm on an iPhone 7 tether downgraded to 14.3 using downr1n. I'm jailbroken via Taurine. 

Installing the IPA via TrollStore, the Bunny app just crashes instantly when opening. Installing the tweak (i installed the rootful version), Discord just runs like Bunny was never even installed, nothing new added to settings.

**Comment by castdrian** [comment]
TS issues arent tweak issues, as for the mod settings not appearing, follow the troubleshooting steps listed in the FAQ before opening issues in that regard

**Comment by Lost-Entrepreneur439** [comment]
I might just be blind, but I don't see a FAQ anywhere.

**Comment by Rairof** [comment]
https://github.com/pyoncord/BunnyTweak/issues/14#issuecomment-2227036042
https://discord.com/channels/1196075698301968455/1225842744291758111

**Comment by Ushie** [comment]
Closing as previous comments indicate that this isn't a tweak issue, join the [Discord server](https://discord.gg/uSwXRHuGfs) if you still need help
