### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by 0xmcha** [bunny-mod/BunnyTweak#15]
Bunny 237.0 crashing when installing via TrollStore

**Comment by castdrian** [comment]
TS issues generally aren't related to the tweak, it's a common thing, follow their troubleshooting steps.

**Comment by 0xmcha** [comment]
> TS issues generally aren't related to the tweak, it's a common thing, follow their troubleshooting steps.

so does it work at your end?

**Comment by RemagOfficial** [comment]
im having the same issue, ive installed with trollstore and installed the deb file and tried installing with sideloadly and it still just crashes when i try and open it

**Comment by Ushie** [comment]
Closing as previous comments indicate that this isn't a tweak issue, join the [Discord server](https://discord.gg/uSwXRHuGfs) if you still need help
