### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by quint-x** [bunny-mod/BunnyTweak#17]
I don't get notifications when I install the app. Everything works fine but I just don't get notifications

**Comment by Ushie** [comment]
Hi,

Unfortunately notifications don't work for sideloaded apps on non-jailbroken iPhones, there are ways to get it working but we don't personally know how as we aren't iPhone users

Maybe the r/Jailbreak subreddit or Discord server will be of help

Closing as this is out of scope

**Comment by castdrian** [comment]
That is incorrect, you do simply need to sign the application with a certificate that has the notification entitlement enabled, however out of scope for gh issue discussions.
