### ISSUE TITLE
AltStore installation failing

### ISSUE THREAD

**Issue by gdude2002** [bunny-mod/BunnyTweak#29]
Non-rooted iPhone 16 Pro Max on iOS 18.1, using AltServer side-loading on a free account.

When attempting to update to the apparently recently released Bunny version `256.0_67462` via AltStore, I got the following error:

> `AltStore.VerificationError 4`
> Bunny could not be installed. The downloaded version of Bunny does not match the version specified by the source.

The version I currently have installed appears to be `247.2_64408`, targeting commit `e80ab84-main`.

**Comment by castdrian** [comment]
that is a testflight build, I do not reccomend using those except for development purposes
hence, why they get pre-released rather than released
![screenshot](https://adriancastro.dev/lr6f388c1vru.png)

**Comment by gdude2002** [comment]
How am I supposed to know that or filter those builds out when this is all I get? Or, was this build meant to hit the AltStore JSON at all?

![IMG_0204](https://github.com/user-attachments/assets/073f9a13-aa21-44a9-8ae9-65f4c0a814e2) ![IMG_0205](https://github.com/user-attachments/assets/8f29d319-6c25-4193-92a5-991b03a6ee38)

**Comment by castdrian** [comment]
versions including the buildnumber prefixed with an underscore `version_build` are testflight, if you feel like that is suboptimal UX, I can offer moving the testflight builds into a seperate app entry in the altsource json

**Comment by gdude2002** [comment]
AltStore doesn't have a way to pick any version other than the latest for updates, so that might be the optimal approach for those of us that use it.

**Comment by gdude2002** [comment]
That fix didn't work, unfortunately. AltStore now fails to refresh, with the following error:

> **Unable to Check for Updates**
> The source "Pyoncord App Repo" contains multiple apps with the bundle identifier `com.hammerandchisel.discord`.

**Comment by castdrian** [comment]
changed the bundle id (https://github.com/bunny-mod/BunnyTweak/commit/17627dead9cb138e35772e84c85a2794bc5f032a) (I'd reccomend using something else other than altstore though, most other apps have a version selector and don't complain about superficial things like this)

**Comment by gdude2002** [comment]
TrollStore doesn't support iOS 18, and SideStore straight up didn't work for me, otherwise yeah I'd be using something else, haha.

I can confirm that things are working correctly in AltStore now. Thanks for the help!
