### ISSUE TITLE
Opening DMs crashes discord permanently

### ISSUE THREAD

**Issue by pikapeen** [bunny-mod/BunnyTweak#34]
Opening DMs gives rendering issue. Reloading discord in any way makes it useless. It cannot render anything after reloading. 

Although it shouldn't be an issue  with signing, I used a krava cert, tried signing with both the official krava app and scarlet. 

As an apology, take a picture of my cat.
![image](https://github.com/user-attachments/assets/e82bbbcb-7bf3-46af-acf1-9c908bb2c17c)

**Comment by castdrian** [comment]
The tweak does not touch the JavaScript portion of the app.
