### ISSUE TITLE
Please add SideStore repo.

### ISSUE THREAD

**Issue by anoraktrend** [bunny-mod/BunnyTweak#37]
This is a minor request that you include a SideStore formatted repository file. (This is so I can stop having to use appdb + occasionally checking GitHub releases for updates).

**Comment by castdrian** [comment]
an altsource is already available

**Comment by anoraktrend** [comment]
The Alt source repo won’t work in SideStore for some reason.

**Comment by castdrian** [comment]
that’s something you’ll have to take up with them
