### ISSUE TITLE
What Does This Tweak Alter?

### ISSUE THREAD

**Issue by luhgarlicbread** [bunny-mod/BunnyTweak#4]
I’ve installed the tweak, but I don’t notice anything significantly different on Discord? What does this tweak alter? Is it just small QOL features that you might not notice at first? I’m a little confused.

Thanks! God bless.

**Comment by ItsJustJoshDev** [comment]
If your phone is rooted it gives you access to plugins and themes for discord

**Comment by Rico040** [comment]
> What does this tweak alter?

Check user settings, there's should be Plugins, Themes and stuff

**Comment by ItsJustJoshDev** [comment]
![Screenshot_20240505-162610](https://github.com/pyoncord/BunnyTweak/assets/68560159/639b160b-be9d-4afa-aee6-74d254e1dea9)
Something like this

> > What does this tweak alter?
> 
> Check user settings, there's should be Plugins, Themes and stuff

**Comment by castdrian** [comment]
> If your phone is rooted it gives you access to plugins and themes for discord 

My mate this has nothing to do with android and rooted devices.

**Comment by ItsJustJoshDev** [comment]
> > If your phone is rooted it gives you access to plugins and themes for discord
> 
> My mate this has nothing to do with android and rooted devices.

I'ma a dumbass I thought I was in the android repo
https://github.com/pyoncord/BunnyXposed

**Comment by amsryq** [comment]
As the repo description says:
> A tweak to inject Bunny, a mod for Discord's mobile apps.

Once Bunny is injected, you should be able to see the Bunny section as in the screenshot above, and able to install Vendetta plugins (i.e. ones from https://vd-plugins.github.io/web/)

**Comment by luhgarlicbread** [comment]
> As the repo description says:
> 
> > A tweak to inject Bunny, a mod for Discord's mobile apps.
> 
> Once Bunny is injected, you should be able to see the Bunny section as in the screenshot above, and able to install Vendetta plugins (i.e. ones from https://vd-plugins.github.io/web/)

YES! Thank you! This tweak is awesome :D
