### ISSUE TITLE
Unable to install Bunny on iOS 18 Developers Beta

### ISSUE THREAD

**Issue by itsidleboy** [bunny-mod/BunnyTweak#8]
### AltStore - 

> Caption - "Pyoncord App Repo" could not be added to AltStore.
> The source "Pyoncord App Repo" is not supported by this version of AltStore.

![IMG_7923](https://github.com/pyoncord/BunnyTweak/assets/62786811/ac2aa7fe-781d-4707-8696-079d21c8469f)

**Comment by castdrian** [comment]
just manually install it
https://github.com/pyoncord/BunnyTweak/pull/7
